Update dataproc_instance

diff --git a/dataproc_instance b/dataproc_instance
--- a/dataproc_instance
+++ b/dataproc_instance
@@ -1,1 +1,57 @@
-#!/bin/bash red='\e[31m' #အနီရောင် #yellow='\e[0;33m' #Regular Color #yellow='\e[43m' #Background yellow1='\e[0;93m' #High Intensty #yellow='\e[1;93m' #Bold High Intensty #yellow='\e[0;93m' #High Intensty backgrounds #yellow='\e[4;33m' #Underline yellow='\e[1;33m' #Bold gray='\e[90m' #မီးခိုးရောင် green='\e[92m' #အစိမ်းရောင် blue='\e[94m' #အပြာရောင် magenta='\e[95m'#ပန်းခရမ်းရောင် cyan='\e[96m' #စိမ်းပြာရောင် none='\e[0m' #အရောင်မရှိ plain='\033[0m' if [[ -n $1 ]] && [[ $2 == e2-* ]] && [[ -n $3 ]] && [[ -n $4 ]] && [[ -n $5 ]] && [[ -n $6 ]] && [[ -n $7 ]] && [[ $(($(date +%s) - $7)) -lt 120 ]] && [[ $(($(date +%s) - $7)) -ge 0 ]]; then echo -e "${yellow}Creating instance ...${plain}" instance=$(gcloud dataproc clusters create $1 --region $4 --master-machine-type $2 --master-boot-disk-size 500 --num-workers 2 --worker-machine-type $2 --worker-boot-disk-size 500 --image-version $6 --project $5) echo -e "${green}Instance created.${plain}" echo -e "${yellow}Checking firewall rule ...${plain}" if [[ $(gcloud compute firewall-rules list --format='value(allowed)') == *"'IPProtocol': 'all'"* ]]; then echo -e "${green}Firewall rule already exist.${plain}" else echo -e "${yellow}Creating firewall rule ...${plain}" gcloud compute firewall-rules create $3 --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0 --no-user-output-enabled echo -e "${green}Firewall rule created.${plain}" fi #echo -e "\n${green}SSH setup is completed successfully.${plain}\n" #IP=$(wget -qO- ipv4.icanhazip.com) #echo "" #echo -e "\033[1;32m====================================" #echo -e "\033[1;32m 🌺ㅤONLY/:FORYOU&ALLㅤ🌺 " #echo -e "\033[1;32m====================================" #echo "" #echo -e "\033[1;37m◈─────⪧ SSH ACCOUNT ⪦─────◈" #echo "" #echo -e "\033[1;32m◈ Host / IP :⪧ \033[1;31m$IP" #echo -e "\033[1;32m◈ Port :⪧ \033[1;31m22" #echo -e "\033[1;32m◈ Username :⪧ \033[1;31m$5" #echo -e "\033[1;32m◈ Password :⪧ \033[1;31m$6" #echo -e "\033[1;32m◈ Login Limit :⪧ \033[1;31m$sshlimiter" #echo -e "\033[1;32m◈ Expire Date :⪧ \033[1;31m$gui" #echo "" #echo -e "\033[1;37m◈────⪧ ✿ ✿ 4▪0▪4 ✿ ✿ ⪦────◈" #echo "" #echo -e "IP : ${green}$(wget -qO- ipv4.icanhazip.com <<<"$instance")${plain}" echo "" echo -e "${yellow}------------------------------------${plain}" printf "Developed the script by \n" echo -e "${yellow}------------------------------------${plain}" echo -e "${yellow1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}" echo -e "${cyan} ___ ___ ________ ___ ___ ${plain}" echo -e "${cyan}|\ \ |\ \ |\ __ \ |\ \ |\ \ ${plain}" echo -e "${cyan}\ \ \|_\ \ \ \ \|\ \ \ \ \|_\ \ ${plain}" echo -e "${cyan} \ \______ \ \ \ \/\ \ \ \______ \ ${plain}" echo -e "${cyan} \|_____|\ \ \ \ \/\ \ \|_____|\ \ ${plain}" echo -e "${cyan} \ \__\ \ \_______\ \ \__\ ${plain}" echo -e "${cyan} \|__| \|_______| \|__| ${plain}" echo -e "${yellow1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}" echo -e "${cyan}i am forbidden 🙄 ${plain}" else echo -e "${red}Token is invalid or expired. Contact the developer https://t.me/seriousvs for more information.${plain}" fi
+#!/bin/bash
+
+plain='\033[0m'
+
+#စာလုံးအရောင်များ(Server Message)
+red='\e[31m'    #အနီရောင်
+yellow='\e[33m' #အဝါရောင်
+gray='\e[90m'   #မီးခိုးရောင်
+green='\e[92m'  #အစိမ်းရောင်
+blue='\e[94m'   #အပြာရောင်
+magenta='\e[95m'#ပန်းခရမ်းရောင်
+cyan='\e[96m'   #စိမ်းပြာရောင်
+none='\e[0m'    #အရောင်မရှိ
+
+#SSH USER LIMIT သတ်မှတ်ရန်
+#sshlimiter="300"
+
+#ရက်ကန့်သက်ရန်(Qwiklab အတွက်မို့ 2-DAY ပုံသေထားရပါသည်)
+#dias="2"
+# $1: username, $2: password, $3: limit, $4: day, $5: message, $6: token
+
+# check root
+[[ $EUID -ne 0 ]] && echo -e "${red}Error: ${plain} You must use root user to run this script!\n" && exit 1
+
+if [[ -n $6 ]] && [[ $(($(date +%s) - $6)) -lt 120 ]] && [[ $(($(date +%s) - $6)) -ge 0 ]]; then
+
+sed -i 's/#\?AllowTcpForwarding .*/AllowTcpForwarding yes/' /etc/ssh/sshd_config && sed -i 's/#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config && sed -i 's/#\?Banner .*/Banner \/etc\/ssh\/gcp_404/' /etc/ssh/sshd_config && /etc/init.d/ssh restart;
+echo "$5" | tee /etc/ssh/gcp_404 >/dev/null
+sizepass=$(echo ${#2})
+[[ $sizepass -lt 3 ]] && {
+ echo -e "\n${cor1}Short password!, use at least 3 characters${scor}\n"
+ exit 1
+}
+final=$(date "+%Y-%m-%d" -d "+$4 days")
+gui=$(date "+%d/%m/%Y" -d "+$4 days")
+pass=$(perl -e 'print crypt($ARGV[0], "password")' $2)
+useradd -e $final -M -s /bin/false -p $pass $1 >/dev/null
+echo "$2" >/etc/$1
+#echo "$1:$2" | chpasswd
+echo "$1 $3" >>/root/usuarios.db
+IP=$(wget -qO- ipv4.icanhazip.com)
+echo ""
+echo -e "\033[1;32m===================================="
+echo -e "\033[1;32m   🌺ㅤONLY/:FORYOU&ALLㅤ🌺  " 
+echo -e "\033[1;32m===================================="
+echo ""
+echo -e "\033[1;37m◈─────⪧ SSH ACCOUNT ⪦─────◈"
+echo ""
+echo -e "\033[1;32m◈ Host / IP   :⪧  \033[1;31m$IP"
+echo -e "\033[1;32m◈ Port        :⪧  \033[1;31m22"
+echo -e "\033[1;32m◈ Username    :⪧  \033[1;31m$1"
+echo -e "\033[1;32m◈ Password    :⪧  \033[1;31m$2"
+echo -e "\033[1;32m◈ Login Limit :⪧  \033[1;31m$3"
+echo -e "\033[1;32m◈ Expire Date :⪧  \033[1;31m$gui"
+echo ""
+echo -e "\033[1;37m◈────⪧ ✿ ✿ 4▪0▪4 ✿ ✿ ⪦────◈"
+echo ""
